export type CronogramaLeilao = {
  data: string        // YYYY-MM-DD
  diaSemana: string
  hora: string
  nome: string
  criador: string
  presencial: string  // VIRTUAL | PRESENCIAL | EXPOGRANDE | EXPOZEBU | ''
  leiloeira: string
  raca: string
  qtdAnimais: number | null
  sexo: string
  comissao: string
  contrato: string    // SIM | NÃO | ''
  faturamentoPrevisto: number | null
  faturamentoRealizado: number | null
  vendaBula: number | null
  comissaoReceber: string
  recebido: string    // SIM | NÃO | ''
}

export const CRONOGRAMA_2026: CronogramaLeilao[] = [
  // ─── JANEIRO ───────────────────────────────────────────────────────────────
  {
    data: '2026-01-25', diaSemana: 'Domingo', hora: '10:00',
    nome: 'NELORE CRISPIM', criador: 'NELORE CRISPIM',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO', qtdAnimais: null,
    sexo: '', comissao: '', contrato: '', faturamentoPrevisto: null,
    faturamentoRealizado: null, vendaBula: null, comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-01-27', diaSemana: 'Terça-feira', hora: '19:30',
    nome: 'MATA BONITA - REPRODUTORES', criador: 'NELORE MATA BONITA',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO', qtdAnimais: null,
    sexo: '', comissao: '', contrato: '', faturamentoPrevisto: null,
    faturamentoRealizado: null, vendaBula: null, comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-01-29', diaSemana: 'Quinta-feira', hora: '19:30',
    nome: 'TOUROS BEEM', criador: 'NELORE BEEM',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO', qtdAnimais: null,
    sexo: 'TOUROS', comissao: '', contrato: '', faturamentoPrevisto: null,
    faturamentoRealizado: null, vendaBula: null, comissaoReceber: '', recebido: '',
  },

  // ─── FEVEREIRO ─────────────────────────────────────────────────────────────
  {
    data: '2026-02-01', diaSemana: 'Domingo', hora: '14:00',
    nome: 'LEILÃO KATAYAMA - ABERTURA DE SAFRA', criador: 'NELORE KATAYAMA',
    presencial: 'VIRTUAL', leiloeira: 'CENTRAL LEILOES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-03', diaSemana: 'Terça-feira', hora: '17:30',
    nome: 'SÓ CRIADOR', criador: '',
    presencial: '', leiloeira: 'BULA REMATES', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-07', diaSemana: 'Sábado', hora: '09:00',
    nome: 'LEILÃO PARTNER RG & ABS - 1ª ETAPA', criador: 'NELORE RG',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-08', diaSemana: 'Domingo', hora: '09:00',
    nome: 'LEILÃO PARTNER RG & ABS - 2ª ETAPA', criador: 'NELORE RG',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-11', diaSemana: 'Quarta-feira', hora: '17:30',
    nome: 'SÓ CRIADOR OU CORTE PREMIUM', criador: '',
    presencial: '', leiloeira: 'BULA REMATES', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-20', diaSemana: 'Sexta-feira', hora: '17:00',
    nome: 'LEILÃO GRIFES MS', criador: '',
    presencial: '', leiloeira: 'BULA REMATES', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-23', diaSemana: 'Segunda-feira', hora: '20:00',
    nome: 'LEILÃO SEMANA DA GENÉTICA GUADALUPE - DIA 1', criador: 'GUADALUPE AGROPECUÁRIA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-24', diaSemana: 'Terça-feira', hora: '20:00',
    nome: 'LEILÃO SEMANA DA GENÉTICA GUADALUPE - DIA 2', criador: 'GUADALUPE AGROPECUÁRIA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-24', diaSemana: 'Terça-feira', hora: '19:30',
    nome: '7º LEILÃO NELORE BAHIA PREMIUM', criador: 'NELORE BAHIA',
    presencial: 'VIRTUAL', leiloeira: 'AGRESTE LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS E FÊMEAS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-02-25', diaSemana: 'Quarta-feira', hora: '20:00',
    nome: 'LEILÃO SEMANA DA GENÉTICA GUADALUPE - DIA 3', criador: 'GUADALUPE AGROPECUÁRIA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },

  // ─── MARÇO ─────────────────────────────────────────────────────────────────
  {
    data: '2026-03-01', diaSemana: 'Domingo', hora: '09:00',
    nome: 'LEILÃO TOUROS MATINHA', criador: 'LEILÃO TOUROS MATINHA',
    presencial: '', leiloeira: 'PROGRAMA LEILÕES', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-03', diaSemana: 'Terça-feira', hora: '17:00',
    nome: 'CORTE LOG BRASIL 2.000', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-03', diaSemana: 'Terça-feira', hora: '19:30',
    nome: 'NELORE BARRA DO DIA', criador: 'NELORE BARRA DO DIA',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-06', diaSemana: 'Sexta-feira', hora: '17:00',
    nome: 'LEILÃO DE CORTE SÓ CRIADOR', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-07', diaSemana: 'Sábado', hora: '',
    nome: 'TOUROS NAVIRAI PARÁ', criador: 'NAVIRAÍ',
    presencial: '', leiloeira: '', raca: '',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-08', diaSemana: 'Domingo', hora: '',
    nome: 'TOUROS EAO', criador: 'EAO AGROPECUÁRIA',
    presencial: '', leiloeira: '', raca: '',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-09', diaSemana: 'Segunda-feira', hora: '',
    nome: 'MATRIZES EAO', criador: 'EAO AGROPECUÁRIA',
    presencial: '', leiloeira: '', raca: '',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-13', diaSemana: 'Sexta-feira', hora: '17:00',
    nome: 'GRIFES MS - RIBALTA', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-15', diaSemana: 'Domingo', hora: '09:00',
    nome: 'REPRODUTORES CAMPARINO', criador: 'FAZENDA CAMPARINO',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-15', diaSemana: 'Domingo', hora: '09:00',
    nome: 'LS AGROPECUÁRIA', criador: 'LS AGROPECUÁRIA',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-16', diaSemana: 'Segunda-feira', hora: '20:00',
    nome: 'MATRIZES CAMPARINO', criador: 'FAZENDA CAMPARINO',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-17', diaSemana: 'Terça-feira', hora: '17:00',
    nome: 'SÓ CRIADOR', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-18', diaSemana: 'Quarta-feira', hora: '',
    nome: '4º LEILÃO AGROPECUÁRIA LAGOA DOS PATOS', criador: 'AGROPECUÁRIA LAGOA DOS PATOS',
    presencial: '', leiloeira: '', raca: '',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-19', diaSemana: 'Quinta-feira', hora: '',
    nome: 'NELORE VC', criador: 'NELORE VC',
    presencial: '', leiloeira: '', raca: '',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-20', diaSemana: 'Sexta-feira', hora: '17:00',
    nome: 'GRIFES MS', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-22', diaSemana: 'Domingo', hora: '20:00',
    nome: 'LEILÃO NELORE PARANÁ', criador: 'NELORE PARANÁ',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-23', diaSemana: 'Segunda-feira', hora: '20:00',
    nome: 'LEILÃO KATAYAMA TRIOLOGIA', criador: 'NELORE KATAYAMA',
    presencial: '', leiloeira: 'CENTRAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-23', diaSemana: 'Segunda-feira', hora: '20:00',
    nome: 'DNA MARCONDES', criador: 'DNA MARCONDES',
    presencial: '', leiloeira: 'E-RURAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-24', diaSemana: 'Terça-feira', hora: '20:00',
    nome: 'LEILÃO KATAYAMA TRIOLOGIA', criador: 'NELORE KATAYAMA',
    presencial: '', leiloeira: 'CENTRAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-25', diaSemana: 'Quarta-feira', hora: '20:00',
    nome: 'LEILÃO KATAYAMA TRIOLOGIA', criador: 'NELORE KATAYAMA',
    presencial: '', leiloeira: 'CENTRAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-25', diaSemana: 'Quarta-feira', hora: '20:00',
    nome: 'MEGA GENÉTICA NAVIRAÍ', criador: 'NAVIRAÍ',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-26', diaSemana: 'Quinta-feira', hora: '20:00',
    nome: 'MEGA GENÉTICA NAVIRAÍ', criador: 'NAVIRAÍ',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-27', diaSemana: 'Sexta-feira', hora: '17:00',
    nome: 'SÓ CRIADOR', criador: '',
    presencial: '', leiloeira: 'BULA', raca: 'CORTE',
    qtdAnimais: null, sexo: '', comissao: '', contrato: '',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-29', diaSemana: 'Domingo', hora: '10:30',
    nome: 'BAMBU', criador: 'NELORE BAMBU',
    presencial: '', leiloeira: 'ERURAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-29', diaSemana: 'Domingo', hora: '09:00',
    nome: 'MEGA GENÉTICA NAVIRAÍ', criador: 'NAVIRAÍ',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-30', diaSemana: 'Segunda-feira', hora: '20:00',
    nome: 'MEGA GENÉTICA NAVIRAÍ', criador: 'NAVIRAÍ',
    presencial: '', leiloeira: 'PROGRAMA LEILOES', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },
  {
    data: '2026-03-31', diaSemana: 'Terça-feira', hora: '19:00',
    nome: 'ELITES NB', criador: 'ELITES NB',
    presencial: '', leiloeira: 'ERURAL', raca: 'PO',
    qtdAnimais: null, sexo: '', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: '',
  },

  // ─── ABRIL ─────────────────────────────────────────────────────────────────
  {
    data: '2026-04-02', diaSemana: 'Quinta-feira', hora: '19:30',
    nome: '2º LEILÃO VIRTUAL FB AGRO', criador: 'FAZENDA BELA ROSA',
    presencial: 'VIRTUAL', leiloeira: 'E-RURAL', raca: 'Nelore Padrão',
    qtdAnimais: 40, sexo: 'FÊMEAS', comissao: '2% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-04-05', diaSemana: 'Domingo', hora: '09:00',
    nome: 'NOVILHOTAS TOP MATINHA', criador: 'RANCHO DA MATINHA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '0,33% do Faturamento + 5% da venda', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-04-06', diaSemana: 'Segunda-feira', hora: '19:30',
    nome: 'LEILÃO FLOC', criador: 'NELORE FLOC',
    presencial: 'VIRTUAL', leiloeira: 'AGRESTE LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-04-09', diaSemana: 'Quinta-feira', hora: '13:00',
    nome: 'TOKA JAKARÉ - 3 NASCENTES', criador: 'TOKA JAKARÉ - 3 NASCENTES',
    presencial: 'EXPOGRANDE', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: 76, sexo: 'FÊMEAS', comissao: '1% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: 1306080, vendaBula: null,
    comissaoReceber: '1% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-04-11', diaSemana: 'Sábado', hora: '13:00',
    nome: 'LEILÃO IPB PRIME', criador: 'NELORE IPB',
    presencial: 'EXPOGRANDE', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: 29, sexo: 'FÊMEAS', comissao: '1% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: 854700, vendaBula: null,
    comissaoReceber: '1% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-04-14', diaSemana: 'Terça-feira', hora: '19:30',
    nome: 'NELORE CACHOEIRÃO', criador: 'FAZENDA CACHOEIRÃO',
    presencial: 'EXPOGRANDE', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: 31, sexo: 'FÊMEAS', comissao: '1% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: 1434000, vendaBula: null,
    comissaoReceber: '1% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-04-19', diaSemana: 'Domingo', hora: '09:00',
    nome: 'FÊMEAS JMP', criador: 'NELORE JMP',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 160, sexo: 'FÊMEAS', comissao: '0,5% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: 10373300, vendaBula: 410400,
    comissaoReceber: '0,5% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-04-19', diaSemana: 'Domingo', hora: '09:00',
    nome: 'TOUROS TERRA BRAVA', criador: 'FAZENDA TERRA BRAVA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 200, sexo: 'MACHOS', comissao: '5% da venda', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: 138600,
    comissaoReceber: '5% da venda', recebido: 'NÃO',
  },
  {
    data: '2026-04-22', diaSemana: 'Quarta-feira', hora: '20:00',
    nome: 'LEILÃO MRA', criador: 'NELORE MRA',
    presencial: 'VIRTUAL', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: 50, sexo: 'FÊMEAS', comissao: '1% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '1% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-04-28', diaSemana: 'Terça-feira', hora: '20:00',
    nome: 'LEILÃO MATINHA EXPOZEBU - EFICIÊNCIA', criador: 'RANCHO DA MATINHA',
    presencial: 'EXPOZEBU', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 30, sexo: 'FÊMEAS', comissao: 'A DEFINIR', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-04-30', diaSemana: 'Quinta-feira', hora: '20:00',
    nome: 'CAMPARINO EXPOZEBU', criador: 'FAZENDA CAMPARINO',
    presencial: 'EXPOZEBU', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS',
    comissao: 'Tabela: <10% → 0,5%; 10-15% → 0,75%; 15-20% → 1%; >20% → 1,5%',
    contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },

  // ─── MAIO ──────────────────────────────────────────────────────────────────
  {
    data: '2026-05-02', diaSemana: 'Sábado', hora: '09:00',
    nome: 'LEILÃO DOADORAS, ASPIRAÇÕES, MATRIZES E BEZERRAS EAO',
    criador: 'EAO AGROPECUÁRIA',
    presencial: 'EXPOZEBU', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 150, sexo: 'FÊMEAS', comissao: '0,33% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '0,33% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-05-03', diaSemana: 'Domingo', hora: '09:00',
    nome: 'TOUROS EAO', criador: 'EAO AGROPECUARIA',
    presencial: 'EXPOZEBU', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 180, sexo: 'MACHOS', comissao: '0,33% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '0,33% do Fat.', recebido: 'NÃO',
  },
  {
    data: '2026-05-05', diaSemana: 'Terça-feira', hora: '',
    nome: 'LEILÃO FAZENDA GAROA', criador: '',
    presencial: 'VIRTUAL', leiloeira: 'AGRESTE LEILÕES', raca: 'Nelore Pintado',
    qtdAnimais: 40, sexo: 'FÊMEAS', comissao: '1% do faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-05', diaSemana: 'Terça-feira', hora: '',
    nome: 'MATINHA EMBRIO', criador: 'RANCHO DA MATINHA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'EMBRIÕES', comissao: 'A DEFINIR', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-07', diaSemana: 'Quinta-feira', hora: '19:00',
    nome: 'LEILÃO MATRIZES SANTA FÉ', criador: 'NELORE SANTA FÉ',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: 35, sexo: 'FÊMEAS', comissao: '1% do faturamento + 3% da venda', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-09', diaSemana: 'Sábado', hora: '12:00',
    nome: 'NELORE KITO / MRA - 4R', criador: 'NELORE KITO - MRA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '1% do faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-13', diaSemana: 'Quarta-feira', hora: '19:00',
    nome: 'GRUPO RIBALTA', criador: 'GRUPO RIBALTA',
    presencial: 'VIRTUAL', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '1% do faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-14', diaSemana: 'Quinta-feira', hora: '',
    nome: 'LEILÃO TOUROS SANTA NAZARÉ', criador: 'NELORE SANTA NAZARÉ',
    presencial: 'PRESENCIAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '1% do faturamento + 3% da venda', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-17', diaSemana: 'Domingo', hora: '',
    nome: 'MATRIZES MATINHA', criador: 'RANCHO DA MATINHA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: 'A DEFINIR', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-19', diaSemana: 'Terça-feira', hora: '',
    nome: 'GOLDEN BOYS MATINHA', criador: 'RANCHO DA MATINHA',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: 'A DEFINIR', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-21', diaSemana: 'Quinta-feira', hora: '19:00',
    nome: 'NELORE TRESMAR', criador: 'NELORE TRESMAR',
    presencial: 'VIRTUAL', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '1% do faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-24', diaSemana: 'Domingo', hora: '09:30',
    nome: 'NELORE MEAB & MODELO', criador: '',
    presencial: 'VIRTUAL', leiloeira: 'BULA REMATES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '1% do faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-28', diaSemana: 'Quinta-feira', hora: '12:00',
    nome: 'RANCHO DA MATINHA', criador: '',
    presencial: 'VIRTUAL', leiloeira: 'PROGRAMA LEILÕES', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: 'A DEFINIR', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-30', diaSemana: 'Sábado', hora: '',
    nome: 'LS AGROPECUÁRIA', criador: '',
    presencial: 'VIRTUAL', leiloeira: 'E-RURAL', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'MACHOS', comissao: '2% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
  {
    data: '2026-05-31', diaSemana: 'Domingo', hora: '',
    nome: 'LS AGROPECUÁRIA', criador: '',
    presencial: 'VIRTUAL', leiloeira: 'E-RURAL', raca: 'Nelore Padrão',
    qtdAnimais: null, sexo: 'FÊMEAS', comissao: '2% do Faturamento', contrato: 'NÃO',
    faturamentoPrevisto: null, faturamentoRealizado: null, vendaBula: null,
    comissaoReceber: '', recebido: 'NÃO',
  },
]

export const MES_LABELS: Record<string, string> = {
  '2026-01': 'Janeiro',
  '2026-02': 'Fevereiro',
  '2026-03': 'Março',
  '2026-04': 'Abril',
  '2026-05': 'Maio',
}
